name: Deploy AWS Lambda

on: 
  push: 
    branches:
      - main
    paths:
      - 'lambda/'

jobs:
  deploy-lambda: # Name of our job
    runs-on: ubuntu-latest # Specifies the runner
    steps:
    - uses: actions/checkout@v2

    - name: Set Up Python # Sets up python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies # Installs any packages
      run:
        python -m pip install --upgrade pip
        pip install -r lambda/requirements.txt -t lambda/

    - name: Configure AWS Creds # Sets Up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1

    - name: Deploy Lambda Function # Zips lambda dir & updates lambda function
      run: |
        cd lambda
        zip -r lambda.zip .
        aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip
